// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7claGWiQ-zCqeYkVJg81CYTPiER2Y-rk',
    appId: '1:657353234336:web:f11a455409932a168ff6c5',
    messagingSenderId: '657353234336',
    projectId: 'project-skripsi-3fd45',
    authDomain: 'project-skripsi-3fd45.firebaseapp.com',
    storageBucket: 'project-skripsi-3fd45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTaCp8qMbkC3-ImsAxbW6nRqfCmY0dH3k',
    appId: '1:657353234336:android:5802862c35f0a7b18ff6c5',
    messagingSenderId: '657353234336',
    projectId: 'project-skripsi-3fd45',
    storageBucket: 'project-skripsi-3fd45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHlH1YUoOU7Pc-wX5aWR-SmqoAfyx8KFE',
    appId: '1:657353234336:ios:e1df090ea6a22f5b8ff6c5',
    messagingSenderId: '657353234336',
    projectId: 'project-skripsi-3fd45',
    storageBucket: 'project-skripsi-3fd45.firebasestorage.app',
    iosBundleId: 'com.projectskripsi.projectSkripsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHlH1YUoOU7Pc-wX5aWR-SmqoAfyx8KFE',
    appId: '1:657353234336:ios:e1df090ea6a22f5b8ff6c5',
    messagingSenderId: '657353234336',
    projectId: 'project-skripsi-3fd45',
    storageBucket: 'project-skripsi-3fd45.firebasestorage.app',
    iosBundleId: 'com.projectskripsi.projectSkripsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7claGWiQ-zCqeYkVJg81CYTPiER2Y-rk',
    appId: '1:657353234336:web:b3fddd495119d44a8ff6c5',
    messagingSenderId: '657353234336',
    projectId: 'project-skripsi-3fd45',
    authDomain: 'project-skripsi-3fd45.firebaseapp.com',
    storageBucket: 'project-skripsi-3fd45.firebasestorage.app',
  );
}
